POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "username":"buglow1",
    "password": "password",
    "email":"paulo1@hotmail.com"
}

###

POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    
    "password": "password",
    "email":"paulo1@hotmail.com"
}


###

PUT http://localhost:3000/api/user/61388cb837258e091802f998
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzg4Y2I4MzcyNThlMDkxODAyZjk5OCIsImlzQWRtaW4iOiJmYWxzZSIsImlhdCI6MTYzMTEwMTg3NCwiZXhwIjoxNjMxNTMzODc0fQ.iKOkVp0qlUfslFrwirrDTCgwG-ABiFDodCX93172hg4

{
    "username": "buglow",
    "password": "password",
    "email":"paulo.busy@hotmail.com"
}

###

GET http://localhost:3001/api/movie/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzljYmU4MmYyNzNkZTU2ZDk1ODc4OSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYzMTcxMDgyOCwiZXhwIjoxNjMyMTQyODI4fQ.KRgyj17zZFxE8ZRRoPPrO1QTbV5yx9J7L0WizNGL0ZA